select
    id as claim_transaction_id,
    claimid as claim_id,
    chargeid as charge_id,
    patientid as patient_id,
    type as transaction_type,
    amount,
    method as transaction_method,
    fromdate as from_date,
    todate as to_date,
    placeofservice as place_of_service,
    procedurecode as procedure_code,
    modifier1 as modifier_1,
    modifier2 as modifier_2,
    diagnosisref1 as diagnosis_ref_1,
    diagnosisref2 as diagnosis_ref_2,
    diagnosisref3 as diagnosis_ref_3,
    diagnosisref4 as diagnosis_ref_4,
    units,
    departmentid as department_id,
    notes,
    unitamount as unit_amount,
    transferoutid as transfer_out_id,
    transfertype as transfer_type,
    payments,
    adjustments,
    transfers,
    outstanding,
    appointmentid as appointment_id,
    linenote as line_note,
    patientinsuranceid as patient_insurance_id,
    feescheduleid as fee_schedule_id,
    providerid as provider_id,
    supervisingproviderid as supervising_provider_id
from {{ source('raw_healthcare', 'claims_transactions') }}