select
    id as patient_id,
    birthdate as birth_date,
    deathdate as death_date,
    ssn,
    drivers as drivers_license,
    passport as passport_number,
    prefix,
    first as first_name,
    middle as middle_name,
    last as last_name,
    suffix,
    maiden as maiden_name,
    marital as marital_status,
    race,
    ethnicity,
    gender,
    birthplace,
    address,
    city,
    state,
    county,
    fips,
    zip,
    lat as latitude,
    lon as longitude,
    healthcare_expenses,
    healthcare_coverage,
    income
from {{ source('raw_healthcare', 'patients') }}